import Head from "next/head";
import React from "react";
import Footer from "../Footer";
import Header from "../Header";

const PageLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>CIRCEYA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default PageLayout;
